base/urls.py
from django.urls import path
from .import views

urlpatterns=[
    path('',views.home,name="home"),
    path('posts/',views.posts,name="posts"),
    path('post/<slug:slug>/',views.post,name="post"),
    path('profile/',views.profile,name="profile"),
    #crud
    path('create_post/',views.createPost,name="create_post"),
    path('update_post/<slug:slug>/',views.updatePost,name="update_post"),
    path('delete_post/<slug:slug>/',views.deletePost,name="delete_post"),
]

kanak/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField

class Tag(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self):
        return self.name
        

class Post(models.Model):
    headline=models.CharField(max_length=200)
    sub_headline=RichTextUploadingField(blank=True,null=True)
    thumbnail=models.ImageField(null=True,blank=True)
    body=RichTextUploadingField(blank=True,null=True)
    more_images=models.TextField(blank=True,null=True)
    created=models.DateTimeField(auto_now_add=True)
    active=models.BooleanField(default=False)
    featured=models.BooleanField(default=False)
    tags=models.ManyToManyField(Tag,null=True)
    slug=models.SlugField(blank=True,null=True)

    def __str__(self):
        return self.headline

    def save(self,*args,**kwargs):
        if self.slug == None:
            slug=slugify(self.headline)
            has_slug=Post.objects.filter(slug=slug).exists()
            count=1
            while has_slug:
                count +=1
                slug=slugify(self.headline) + '-' + str(count)
                has_slug=Post.objects.filter(slug=slug).exists()
            self.slug=slug
        super().save(*args,**kwargs)

base/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post

class PostForm(ModelForm):
    class Meta:
        model=Post
        fields='__all__'

        widgets={
            'tags':forms.CheckboxSelectMultiple(),
        }

base/views.py
from django.shortcuts import render,redirect
from .models import Post,Tag
from .forms import PostForm
from .filters import PostFilter
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger


# Create your views here.
def home(request):
    posts=Post.objects.all()[0:3]
    context={'posts':posts}
    return render(request,'base/index.html',context)

def posts(request):
    posts=Post.objects.all()
    myfilter=PostFilter(request.GET,queryset=posts)
    posts=myfilter.qs

    #pagination
    page=request.GET.get('page')
    paginator=Paginator(posts,3)
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)

    context={'posts':posts,'myfilter':myfilter}
    return render(request,'base/posts.html',context)

def post(request,slug):
    post=Post.objects.get(slug=slug)
    context={'post':post}
    return render(request,'base/post.html',context)

def profile(request):
    return render(request,'base/profile.html')

#CRUD VIEWS
@login_required(login_url="home")
def createPost(request):
    form=PostForm()
    if request.method == 'POST':
        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context={'form':form}
    return render(request,'base/post_form.html',context)

@login_required(login_url="home")
def updatePost(request,slug):
    post=Post.objects.get(slug=slug)
    form=PostForm(instance=post)
    if request.method == 'POST':
        form=PostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context={'form':form}
    return render(request,'base/post_form.html',context)


@login_required(login_url="home")
def deletePost(request,slug):
    post=Post.objects.get(slug=slug)
    if request.method == 'POST':
        post.delete()
        return redirect('posts')

    context={'item':post}
    return render(request,'base/delete.html',context)

base/templates/base/delete.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
    <div class="main-container">
        <form action="" method="POST">
            {% csrf_token %}
            <p>Are you want to delete the {{ item }}?</p>
            <input class="btn btn-danger" value="confirm" type="submit">
        </form>
    </div>

{% endblock %}

base/templates/base/home.html
{% extends 'base/main.html' %}

{% block content %}
<h1> home </h1>
{% endblock %}

base/templates/base/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title> Kanak hassan </title>


	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
	<style>
		p.impact {
  font-family: Impact, Charcoal, sans-serif;
}
	</style>
</head>
<body>

	<section class="s1">
		<div class="main-container">
			<div class="greeting-wrapper">
				<h1>Hi, I'm Md. Kamruzzaman
				</h1>
			</div>


			<div class="intro-wrapper">
				{% include 'base/navbar.html' %}

				<div class="left-column">
					<img id="profile_pic" src="{% static 'images/kanak.jpg' %}">
					<h5 style="text-align: center;line-height: 0;">Personalize Theme</h5>

					<div id="theme-options-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot"></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
						<div data-mode="green" id="green-mode" class="theme-dot"></div>
						<div data-mode="purple" id="purple-mode" class="theme-dot"></div>
					</div>

					<p id="settings-note">*Theme settings will be saved for<br>your next visit</p>
				</div>

				<div class="right-column">

					<!-- <div id="preview-shadow"> -->
						<div id="preview" style="width: 500px;height: 150px;font-family:Arial, Helvetica, sans-serif;font-size: 17px;">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<!-- <h3>What I Do</h3>
							<p>I was a lead developer in a past life, now I enjoy teaching courses. fdvdjvvfjj shvdss
								vsidovhvsv ujsvhjjos suvhvh sdiuhsvhisn  shsdjdsjk jsjhkshfd sdfvkdkjjk
							</p> -->
							<!-- <h2>Basic HTML Table</h2> -->

									<table style="width:130%;font-size: 120%;">
							
									<tr>
										<td><b>Mobile</b> </td>
										<td>01766883332 </td>				
									</tr>
									<tr>
										<td><b>Email</b> </td>
										<td>kanakcsepust07@gmail.com</td>
							
									</tr>
									<tr>
										<td><b>Github</b> </td>
										<td>https://github.com/jankanak</td>
									</tr>
									
									<tr>
										<td><b>Skype</b></td>
										<td>kanaktonu</td>	
									</tr>

									<tr>
										<td><b>LinkedIn</b> </td>
										<td>Md. Kamruzzaman</td>
									</tr>

									</table>
							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>
						</div>
					<!-- </div> -->
				</div>
			</div>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">

			<div class="about-wrapper">
				<div class="about-me">
					<h4>CAREER OBJECTIVES 
					</h4>

					

					<p>To pursue a challenging carrier and be part of a professional organization that gives me the
						scope to enhance my skills, knowledge and learning experiences to build useful software
						that has business value and to contribute in the welfare of the institution.</p>


					<hr>

					<h4>TOP EXPERTISE</h4>

					<p>Fullstack developer with primary focus on Django + React: <a target="_blank" href="{% static 'resume.pdf' %}">Download Resume</a></p>

					<div id="skills">
						<ul>
							<li>Python</li>
							<li>Django</li>
							<li>JavaScript</li>
							<li>Bootstrap</li>
							<li>Pandas</li>
						</ul>

						<ul>
							<li>R</li>
							<li>Git and GitHub</li>
							<li>Docker</li>
							<li>Selenium</li>
							<li>BeautifulSoup</li>
						</ul>

					</div>

				</div>

				<div class="about-me">
					<h4>Research Work 	</h4>
					<p >
						<strong>Topics:</strong> Analyse Exporting Goods and Services of Bangladesh Using Data Mining Technique.<br>
						<strong>Outcome:</strong><br>

						• The impact of exports goods and services on the economic growth of Bangladesh.<br>
						• To find out the factor that is responsible for exporting goods and services from Bangladesh.<br>														
						• To find long run relationship between exports goods and services and its
						reasoning factor<br>


					</p>
					
					<p>
						<strong>Technical Competency:</strong> R, Numpy, pandas.
					</p>
					<p>
						<strong> Link:</strong> <a href="https://github.com/jankanak/Thesis-Conference-paper"> https://github.com/jankanak/Thesis-Conference-paper </a>
					</p>
			
				</div>
			</div>

		</div>
	</section>

	<section class="s1">
		<div class="main-container">
			<h3 style="text-align: center;">Some of my past projects</h3>

			<div class="post-wrapper">
				{% for post in posts %}

				<div>
					<div class="post">
						<img class="thumbnail" src="{{ post.thumbnail.url }}">
						<div class="post-preview">
							<h5 class="post-title">{{ post.headline }}</h5>
							<p class="post-intro">{{ post.sub_headline|safe }}</p>
							{% for tag in post.tags.all %}
							<span class="tag" style="background-color: black; font-size: 15px;padding: 2px 5px; border-radius: 5px;">{{ tag }}</span>
							{% endfor %}
							<hr>
							<a href="{% url 'post' post.slug  %}">Read More</a>
						</div>
					</div>
				</div>
				{%  endfor %}


			</div>

			<p align="center">
				<a href="{% url 'posts' %}">View More </a>
				
			</p>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">

			<div class="about-wrapper">
				<div class="about-me">
					<h4>Experiences</h4>
					<table style="width: 500px;font-family:Arial, Helvetica, sans-serif;font-size: 17px;padding-top: 10px; padding-bottom:10px;padding-left:10px;background-color: var(--previewShadow);">
							
						<tr>
							<td><strong style="padding-right: 10px;">Institute</strong>  </td>
							<td>Pabna Engineering College, Pabna, Bangladesh.  </td>				
						</tr>
						<tr>
							<td><strong>Position</strong>	 </td>
							
							<td>Lecturer</td>
				
						</tr>
						<tr>
							<td><strong>Duration</strong></td>
							<td>September, 2019 ~ Now</td>
						</tr>
						

						</table>
						<h4>REFERENCES 
						</h4>
						<p style= "padding-left:5px;padding-top:5px;color:black;width: 500px;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;font-size: 17px;padding-top: 10px; padding-bottom:10px;padding-left:10px;background-color: var(--previewShadow);">
							Md. Mahmudul Hasan <br>
							Assistant Professor<br>
							Department of Computer Science and Engineering<br>
							Pabna University of Science & Technology.<br>
							Mobile: 01722044641 <br>
						</p>


				</div>

				<div class="about-me">
					<h4> EDUCATIONAL QUALIFICATIONS 	</h4>
					<div class="bsc" style="padding-top: 0%;">
						<h5>Bachelor of Science (BSC) </h5>	
						<div style="padding-top: 5px; padding-bottom:5px;padding-left:5px;background-color: var(--previewShadow);">
							<table style="width:130%;font-size: 120%;">
						
								<tr>
									<td><b>University</b> </td>
									<td> Pabna University of Science and Technology  </td>				
								</tr>
								<tr>
									<td><b>Department </b> </td>
									<td>Computer Science & Engineering </td>
						
								</tr>
								<tr>
									<td><b>Result</b> </td>
									<td>GPA 3.44 (in scale of 4) </td>
								</tr>
								
		
							</table>
						</div>
				
					</div>
					<div class="bsc" >
						<h5>Higher Secondary Certificate (HSC) </h5>	
						<div style="padding-top: 5px; padding-bottom:5px;padding-left:5px;background-color: var(--previewShadow);">

							<table style="width:130%;font-size: 120%;">
						
								<tr>
									<td><b>College </b> </td>
									<td>Govt. Shaheed Bulbul College,Pabna.  </td>				
								</tr>
								<tr>
									<td><b>Result  </b> </td>
									<td> GPA 5.00 (in scale of 5)</td>
						
								</tr>
							
		
							</table>
						</div>
			
					</div>
					<div class="bsc">
						<h5>Secondary School Certificate (SSC)  </h5>	
						<div  style="padding-top: 5px; padding-bottom:5px;padding-left:5px;background-color: var(--previewShadow);">
							<table style="width:130%;font-size: 120%;">
						
								<tr>
									<td ><b>School  </b> </td>
									<td>Khatib Abdul Zahid High School & College.  </td>				
								</tr>
								<tr>
									<td><b>Result  </b> </td>
									<td> GPA 5.00 (in scale of 5)</td>
						
						
								</tr>
							
		
							</table>
						</div>
				
					</div>
					
					
				</div>
			</div>

		</div>
	</section>






	
	<script type="text/javascript">
		let static ="{% static 'css' %}"
	</script>

	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

base/templates/base/main.html
{% load static %}
<html>

    <head>
        <title>kanak hassan </title>
        <!-- CSS only -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	    <link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	    <link id="theme-style" rel="stylesheet" type="text/css" href="">
    </head>

    <body>
        {% include 'base/navbar.html' %}

        {% block content %}
        {% endblock %}
    
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </body>
</html>

base/templates/base/navbar.html
<div class="nav-wrapper">

    <!-- Link around dots-wrapper added after tutorial video -->
    <a href="{% url 'home' %}">
        <div class="dots-wrapper">
            <div id="dot-1" class="browser-dot"></div>
            <div id="dot-2" class="browser-dot"></div>
            <div id="dot-3" class="browser-dot"></div>
        </div>
    </a>
    

    <ul id="navigation">
        <li><a href="{% url 'home' %}#contact">Home</a></li>
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'create_post' %}">Create Post </a></li>
        {% endif %}
    </ul>
</div>

base/templates/base/post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
<div class="main-container">
    <img style="width: 1100px; height: 500px;" src="{{ post.thumbnail.url }}">
    <h1>{{ post.headline }}</h1>
    <h2 style="font-size: 20px;">{{ post.sub_headline|safe }}</h2>
    <p>{{ post.body|safe }} </p>
</div>
{% endblock %}

base/templates/base/post_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style type="css/text">
    #div_id_tags > div{
        max-height: 100px;
        overflow-y: scroll;
        border: 1px solid #888;
        padding :5px;

    }
</style>

    <div class="main-container">
        <h3>Post form </h3>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form> 
    </div>
{% endblock %}

base/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    #id_tags{
        max-height: 100px;
        overflow-y: scroll;
        border: 1px solid #888888;
        border-radius: 5px;
        padding:5px;
    }
</style>

<div class="main-container">
    <h3 style="text-align: center;padding-bottom: 3%;">Some of my past projects</h3>
    <form method="GET">
        {{ myfilter.form|crispy }}
        <input class="btn btn-primary" type="submit" value="Search">
    </form>

    <div class="post-wrapper">
        {% for post in posts %}

        <div>
            <div class="post">
                <img class="thumbnail" src="{{ post.thumbnail.url }}">
                <div class="post-preview">
                    <h6 class="post-title">{{post.headline}}</h6>
                    <p class="post-intro" style="font-size:10px;">{{ post.body|safe }}</p>
                    {% for tag in post.tags.all %}
                        <span class="tag" style="background-color: black; font-size: 15px; padding-bottom: 2px;">{{ tag }}</span>
                    {% endfor %}
                    <hr>
                    {% if request.user.is_authenticated %}
                    <a style="padding-right:5%;" href="{% url 'update_post' post.slug %}">Edit</a>
                    <a style="padding-right:5%;" href="{% url 'delete_post' post.slug %}">Delete</a>
                    {% endif %}
                    <a href="{% url 'post' post.slug %}">Read More</a>
                
                </div>
            </div>
        </div>

  
        {% endfor %}
    </div>

    <div class="d-flex flex-column m-auto pagination mt-5">
        <nav aria-label="Page navigation">
        <ul class="pagination pg-grey justify-content-center">
            {% if posts.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ posts.previous_page_number }}">&laquo; Previous</a>
                </li>
            {% endif %}
        
            {% for i in posts.paginator.page_range %}
                {% if posts.number == i %}
                    <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                {% else %}
                    <li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            
            {% if posts.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ posts.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ posts.paginator.num_pages }}">Last &raquo;</a>
                </li>
            {% endif %}
        </ul>
        </nav>
        </div>

</div>
{% endblock %}

base/templates/base/profile.html
{% extends 'base/main.html' %}
{% block content %}
<h1>profile</h1>
{% endblock %}